"""empty message

Revision ID: bfecb208eeae
Revises: c61eae8a2b8d
Create Date: 2021-10-20 19:57:20.850694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfecb208eeae'
down_revision = 'c61eae8a2b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('item_price', sa.Integer(), nullable=False))
    op.add_column('cart_items', sa.Column('item_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'item_quantity')
    op.drop_column('cart_items', 'item_price')
    # ### end Alembic commands ###
