"""empty message

Revision ID: c61eae8a2b8d
Revises: 4372d20c12eb
Create Date: 2021-10-20 18:26:33.734371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61eae8a2b8d'
down_revision = '4372d20c12eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist_items', sa.Column('item_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist_items', 'item_name')
    # ### end Alembic commands ###
