"""empty message

Revision ID: 22041800b4f1
Revises: a872f0cfacd6
Create Date: 2021-10-25 11:19:25.426385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22041800b4f1'
down_revision = 'a872f0cfacd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist_items', sa.Column('item_gender', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist_items', 'item_gender')
    # ### end Alembic commands ###
