"""empty message

Revision ID: 0b9fabcabe10
Revises: 2655b6ab3abe
Create Date: 2021-10-21 20:08:50.000342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9fabcabe10'
down_revision = '2655b6ab3abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist_items', sa.Column('item_price', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist_items', 'item_price')
    # ### end Alembic commands ###
