"""empty message

Revision ID: 8bad8bd75829
Revises: ad20fb467d80
Create Date: 2021-10-21 11:40:14.663621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bad8bd75829'
down_revision = 'ad20fb467d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_items_user_id_fkey', 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key('cart_items_user_id_fkey', 'cart_items', 'carts', ['user_id'], ['id'])
    # ### end Alembic commands ###
