"""empty message

Revision ID: bb467123bfa3
Revises: 0b9fabcabe10
Create Date: 2021-10-22 10:25:03.028910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb467123bfa3'
down_revision = '0b9fabcabe10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('item_image', sa.String(length=2000), nullable=False))
    op.add_column('items', sa.Column('color2', sa.String(length=255), nullable=True))
    op.add_column('items', sa.Column('color3', sa.String(length=255), nullable=True))
    op.add_column('items', sa.Column('image1', sa.String(length=2000), nullable=False))
    op.add_column('items', sa.Column('image2', sa.String(length=2000), nullable=False))
    op.add_column('items', sa.Column('image3', sa.String(length=2000), nullable=False))
    op.add_column('wishlist_items', sa.Column('item_image', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist_items', 'item_image')
    op.drop_column('items', 'image3')
    op.drop_column('items', 'image2')
    op.drop_column('items', 'image1')
    op.drop_column('items', 'color3')
    op.drop_column('items', 'color2')
    op.drop_column('cart_items', 'item_image')
    # ### end Alembic commands ###
