"""empty message

Revision ID: c11d218bba6d
Revises: 22041800b4f1
Create Date: 2021-10-26 07:55:34.630410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c11d218bba6d'
down_revision = '22041800b4f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'image2',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    op.alter_column('items', 'image3',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'image3',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    op.alter_column('items', 'image2',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    # ### end Alembic commands ###
