"""empty message

Revision ID: f7ff3e1dc775
Revises: 08de9ad82c14
Create Date: 2021-10-23 14:42:41.387938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ff3e1dc775'
down_revision = '08de9ad82c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'updated_at')
    # ### end Alembic commands ###
