"""empty message

Revision ID: 4372d20c12eb
Revises: d92b5400cca0
Create Date: 2021-10-20 15:37:25.748166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4372d20c12eb'
down_revision = 'd92b5400cca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('cart_id', sa.Integer(), nullable=False))
    op.drop_constraint('cart_items_user_id_fkey', 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['id'])
    op.drop_column('cart_items', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key('cart_items_user_id_fkey', 'cart_items', 'users', ['user_id'], ['id'])
    op.drop_column('cart_items', 'cart_id')
    # ### end Alembic commands ###
