"""empty message

Revision ID: 1f53831b351d
Revises: 8bad8bd75829
Create Date: 2021-10-21 11:43:06.668346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f53831b351d'
down_revision = '8bad8bd75829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('item_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'item_name')
    # ### end Alembic commands ###
